# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/.Xil/Vivado-23320-LAPTOP-H1858A6E/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a75tfgg484-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    D:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.srcs/sources_1/ip/mig_7series_0
    D:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.srcs/sources_1/ip/clk_wiz_0
    D:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.srcs/sources_1/ip/clk_wiz_1
    D:/three_verilog/MIPI_DDR3_HDMI/rtl/fifo/rdata_fifo
    d:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.srcs/sources_1/ip/v_tc_0
    D:/three_verilog/MIPI_DDR3_HDMI/ip/fifo_rd_64_8
    D:/three_verilog/MIPI_DDR3_HDMI/ip/fifo_wr_64_64
    D:/three_verilog/MIPI_DDR3_HDMI/ip/fifo_8_sys
  } {
      C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    D:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.srcs/sources_1/ip/mig_7series_0
    D:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.srcs/sources_1/ip/clk_wiz_0
    D:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.srcs/sources_1/ip/clk_wiz_1
    D:/three_verilog/MIPI_DDR3_HDMI/rtl/fifo/rdata_fifo
    d:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.srcs/sources_1/ip/v_tc_0
    D:/three_verilog/MIPI_DDR3_HDMI/ip/fifo_rd_64_8
    D:/three_verilog/MIPI_DDR3_HDMI/ip/fifo_wr_64_64
    D:/three_verilog/MIPI_DDR3_HDMI/ip/fifo_8_sys
  } {
      D:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/.Xil/Vivado-23320-LAPTOP-H1858A6E/realtime/wdata_fifo_stub.v
      D:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/.Xil/Vivado-23320-LAPTOP-H1858A6E/realtime/mig_7series_0_stub.v
      D:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/.Xil/Vivado-23320-LAPTOP-H1858A6E/realtime/clk_wiz_0_stub.v
      D:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/.Xil/Vivado-23320-LAPTOP-H1858A6E/realtime/clk_wiz_1_stub.v
      D:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/.Xil/Vivado-23320-LAPTOP-H1858A6E/realtime/rdata_fifo_stub.v
      D:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/.Xil/Vivado-23320-LAPTOP-H1858A6E/realtime/v_tc_0_stub.v
      D:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/.Xil/Vivado-23320-LAPTOP-H1858A6E/realtime/fifo_rd_64_8_stub.v
      D:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/.Xil/Vivado-23320-LAPTOP-H1858A6E/realtime/fifo_wr_64_64_stub.v
      D:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/.Xil/Vivado-23320-LAPTOP-H1858A6E/realtime/fifo_8_sys_stub.v
      D:/three_verilog/MIPI_DDR3_HDMI/rtl/MIPI_rx/ECC_Calculate_Haming.v
      D:/three_verilog/MIPI_DDR3_HDMI/rtl/hdmi/Hdmi_top.v
      D:/three_verilog/MIPI_DDR3_HDMI/rtl/TOP/IIC_Camera_Config.v
      D:/three_verilog/MIPI_DDR3_HDMI/rtl/MIPI_rx/Mipi_Byte_Alignment.v
      D:/three_verilog/MIPI_DDR3_HDMI/rtl/MIPI_rx/Mipi_Lane_Alignment.v
      D:/three_verilog/MIPI_DDR3_HDMI/rtl/MIPI_rx/Mipi_Unpacket.v
      D:/three_verilog/MIPI_DDR3_HDMI/rtl/TOP/Mipi_camera_top.v
      D:/three_verilog/MIPI_DDR3_HDMI/rtl/MIPI_rx/Mipi_dphy_rx.v
      D:/three_verilog/MIPI_DDR3_HDMI/rtl/MIPI_rx/Mipi_raw10_depacker.v
      D:/three_verilog/MIPI_DDR3_HDMI/rtl/hdmi/asyn_rst_syn.v
      D:/three_verilog/MIPI_DDR3_HDMI/rtl/axi/axi_dma.v
      D:/three_verilog/MIPI_DDR3_HDMI/rtl/axi/data_joint.v
      D:/three_verilog/MIPI_DDR3_HDMI/rtl/fifo/data_sync_ext.v
      D:/three_verilog/MIPI_DDR3_HDMI/rtl/hdmi/encode.v
      D:/three_verilog/MIPI_DDR3_HDMI/rtl/iic/ov5640_cfg.v
      D:/three_verilog/MIPI_DDR3_HDMI/rtl/iic/ov5640_iic.v
      D:/three_verilog/MIPI_DDR3_HDMI/rtl/hdmi/serializer_10_to_1.v
      D:/three_verilog/MIPI_DDR3_HDMI/rtl/fifo/wdata_rdata_fifo.v
      D:/three_verilog/MIPI_DDR3_HDMI/rtl/TOP/MIPI_DDR3_HDMI_top.v
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top MIPI_DDR3_HDMI_top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "D:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/.Xil/Vivado-23320-LAPTOP-H1858A6E/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
