######################################################################
#
# File name : tb_Mipi_Bayer_2_RGB_simulate.do
# Created on: Wed Dec 13 21:17:16 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L fifo_generator_v13_2_7 -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.tb_Mipi_Bayer_2_RGB xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_Mipi_Bayer_2_RGB_wave.do}

view wave
view structure
view signals

do {tb_Mipi_Bayer_2_RGB.udo}

run 1000ns
