######################################################################
#
# File name : tb_Mipi_Bayer_2_RGB_wave.do
# Created on: Wed Dec 13 21:04:17 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
