# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/three_verilog/MIPI_DDR3_HDMI/sim/MIPI_trans/MIPI_trans.srcs/sources_1/ip/Sfifo_Raw2RGB_w32x1024_r32x1024/Sfifo_Raw2RGB_w32x1024_r32x1024.xci
# IP: The module: 'Sfifo_Raw2RGB_w32x1024_r32x1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/three_verilog/MIPI_DDR3_HDMI/sim/MIPI_trans/MIPI_trans.gen/sources_1/ip/Sfifo_Raw2RGB_w32x1024_r32x1024/Sfifo_Raw2RGB_w32x1024_r32x1024.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sfifo_Raw2RGB_w32x1024_r32x1024'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/three_verilog/MIPI_DDR3_HDMI/sim/MIPI_trans/MIPI_trans.gen/sources_1/ip/Sfifo_Raw2RGB_w32x1024_r32x1024/Sfifo_Raw2RGB_w32x1024_r32x1024_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sfifo_Raw2RGB_w32x1024_r32x1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/three_verilog/MIPI_DDR3_HDMI/sim/MIPI_trans/MIPI_trans.gen/sources_1/ip/Sfifo_Raw2RGB_w32x1024_r32x1024/Sfifo_Raw2RGB_w32x1024_r32x1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sfifo_Raw2RGB_w32x1024_r32x1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/three_verilog/MIPI_DDR3_HDMI/sim/MIPI_trans/MIPI_trans.srcs/sources_1/ip/Sfifo_Raw2RGB_w32x1024_r32x1024/Sfifo_Raw2RGB_w32x1024_r32x1024.xci
# IP: The module: 'Sfifo_Raw2RGB_w32x1024_r32x1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/three_verilog/MIPI_DDR3_HDMI/sim/MIPI_trans/MIPI_trans.gen/sources_1/ip/Sfifo_Raw2RGB_w32x1024_r32x1024/Sfifo_Raw2RGB_w32x1024_r32x1024.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sfifo_Raw2RGB_w32x1024_r32x1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/three_verilog/MIPI_DDR3_HDMI/sim/MIPI_trans/MIPI_trans.gen/sources_1/ip/Sfifo_Raw2RGB_w32x1024_r32x1024/Sfifo_Raw2RGB_w32x1024_r32x1024_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sfifo_Raw2RGB_w32x1024_r32x1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/three_verilog/MIPI_DDR3_HDMI/sim/MIPI_trans/MIPI_trans.gen/sources_1/ip/Sfifo_Raw2RGB_w32x1024_r32x1024/Sfifo_Raw2RGB_w32x1024_r32x1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sfifo_Raw2RGB_w32x1024_r32x1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
