# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.srcs/sources_1/ip/S_fifo_w8x2048_r8x2048/S_fifo_w8x2048_r8x2048.xci
# IP: The module: 'S_fifo_w8x2048_r8x2048' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.gen/sources_1/ip/S_fifo_w8x2048_r8x2048/S_fifo_w8x2048_r8x2048.xdc
# XDC: The top module name and the constraint reference have the same name: 'S_fifo_w8x2048_r8x2048'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.gen/sources_1/ip/S_fifo_w8x2048_r8x2048/S_fifo_w8x2048_r8x2048_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'S_fifo_w8x2048_r8x2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.srcs/sources_1/ip/S_fifo_w8x2048_r8x2048/S_fifo_w8x2048_r8x2048.xci
# IP: The module: 'S_fifo_w8x2048_r8x2048' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.gen/sources_1/ip/S_fifo_w8x2048_r8x2048/S_fifo_w8x2048_r8x2048.xdc
# XDC: The top module name and the constraint reference have the same name: 'S_fifo_w8x2048_r8x2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.gen/sources_1/ip/S_fifo_w8x2048_r8x2048/S_fifo_w8x2048_r8x2048_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'S_fifo_w8x2048_r8x2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
