# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/three_verilog/MIPI_DDR3_HDMI/rtl/MIPI_rx/MIPI_test_top/Rx_test.xdc

# IP: ip/ila_0/ila_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet
