# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/three_verilog/MIPI_DDR3_HDMI/constrain/Rx_test.xdc

# IP: D:/three_verilog/MIPI_DDR3_HDMI/rtl/fifo/rdata_fifo/rdata_fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rdata_fifo || ORIG_REF_NAME==rdata_fifo} -quiet] -quiet

# IP: D:/three_verilog/MIPI_DDR3_HDMI/rtl/fifo/wdata_fifo/wdata_fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wdata_fifo || ORIG_REF_NAME==wdata_fifo} -quiet] -quiet
