# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.runs/synth_1/MIPI_DDR3_HDMI_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param tcl.collectionResultDisplayLimit 0
set_param chipscope.maxJobs 5
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a75tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.cache/wt [current_project]
set_property parent.project_path D:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/three_verilog/fpga_IP_define [current_project]
update_ip_catalog
set_property ip_output_repo d:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  D:/three_verilog/MIPI_DDR3_HDMI/rtl/axi/DMA_Custom.v
  D:/three_verilog/MIPI_DDR3_HDMI/rtl/MIPI_rx/ECC_Calculate_Haming.v
  D:/three_verilog/MIPI_DDR3_HDMI/rtl/image_process/Gamma_06.v
  D:/three_verilog/MIPI_DDR3_HDMI/rtl/hdmi/HDMI_Process_top.v
  D:/three_verilog/MIPI_DDR3_HDMI/rtl/TOP/IIC_Camera_Config.v
  D:/three_verilog/MIPI_DDR3_HDMI/rtl/MIPI_rx/Mipi_Byte_Alignment.v
  D:/three_verilog/MIPI_DDR3_HDMI/rtl/MIPI_rx/Mipi_Lane_Alignment.v
  D:/three_verilog/MIPI_DDR3_HDMI/rtl/MIPI_rx/Mipi_Unpacket.v
  D:/three_verilog/MIPI_DDR3_HDMI/rtl/TOP/Mipi_camera_top.v
  D:/three_verilog/MIPI_DDR3_HDMI/rtl/MIPI_rx/Mipi_dphy_rx.v
  D:/three_verilog/MIPI_DDR3_HDMI/rtl/MIPI_rx/Mipi_raw10_depacker.v
  D:/three_verilog/MIPI_DDR3_HDMI/rtl/image_process/Post_Raw2Rgb.v
  D:/three_verilog/MIPI_DDR3_HDMI/rtl/hdmi/asyn_rst_syn.v
  D:/three_verilog/MIPI_DDR3_HDMI/rtl/axi/data_sync_ext.v
  D:/three_verilog/MIPI_DDR3_HDMI/rtl/hdmi/encode.v
  D:/three_verilog/MIPI_DDR3_HDMI/rtl/iic/ov5640_cfg.v
  D:/three_verilog/MIPI_DDR3_HDMI/rtl/iic/ov5640_iic.v
  D:/three_verilog/MIPI_DDR3_HDMI/rtl/hdmi/serializer_10_to_1.v
  D:/three_verilog/MIPI_DDR3_HDMI/rtl/fifo/wdata_rdata_fifo.v
  D:/three_verilog/MIPI_DDR3_HDMI/rtl/TOP/MIPI_DDR3_HDMI_top.v
}
read_ip -quiet D:/three_verilog/MIPI_DDR3_HDMI/rtl/fifo/rdata_fifo/rdata_fifo.xci
set_property used_in_implementation false [get_files -all d:/three_verilog/project_1.gen/sources_1/ip/rdata_fifo/rdata_fifo.xdc]
set_property used_in_implementation false [get_files -all d:/three_verilog/project_1.gen/sources_1/ip/rdata_fifo/rdata_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/three_verilog/project_1.gen/sources_1/ip/rdata_fifo/rdata_fifo_ooc.xdc]

read_ip -quiet D:/three_verilog/MIPI_DDR3_HDMI/rtl/fifo/wdata_fifo/wdata_fifo.xci
set_property used_in_implementation false [get_files -all d:/three_verilog/project_1.gen/sources_1/ip/wdata_fifo/wdata_fifo.xdc]
set_property used_in_implementation false [get_files -all d:/three_verilog/project_1.gen/sources_1/ip/wdata_fifo/wdata_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/three_verilog/project_1.gen/sources_1/ip/wdata_fifo/wdata_fifo_ooc.xdc]

read_ip -quiet D:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.srcs/sources_1/ip/mig_7series_0/mig_7series_0.xci
set_property used_in_implementation false [get_files -all d:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0.xdc]
set_property used_in_implementation false [get_files -all d:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0_ooc.xdc]

read_ip -quiet D:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet D:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci
set_property used_in_implementation false [get_files -all d:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.gen/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.gen/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc]
set_property used_in_implementation false [get_files -all d:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.gen/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc]

read_ip -quiet D:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.srcs/sources_1/ip/v_tc_0/v_tc_0.xci
set_property used_in_implementation false [get_files -all d:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.gen/sources_1/ip/v_tc_0/v_tc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.gen/sources_1/ip/v_tc_0/v_tc_0_ooc.xdc]

read_ip -quiet D:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.srcs/sources_1/ip/S_fifo_w8x2048_r8x2048/S_fifo_w8x2048_r8x2048.xci
set_property used_in_implementation false [get_files -all d:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.gen/sources_1/ip/S_fifo_w8x2048_r8x2048/S_fifo_w8x2048_r8x2048.xdc]
set_property used_in_implementation false [get_files -all d:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.gen/sources_1/ip/S_fifo_w8x2048_r8x2048/S_fifo_w8x2048_r8x2048_ooc.xdc]

read_ip -quiet D:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.srcs/sources_1/ip/ila_0_1/ila_0.xci
set_property used_in_synthesis false [get_files -all d:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.gen/sources_1/ip/ila_0_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.gen/sources_1/ip/ila_0_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.gen/sources_1/ip/ila_0_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.gen/sources_1/ip/ila_0_1/ila_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/three_verilog/MIPI_DDR3_HDMI/constrain/Rx_test.xdc
set_property used_in_implementation false [get_files D:/three_verilog/MIPI_DDR3_HDMI/constrain/Rx_test.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental D:/three_verilog/MIPI_DDR3_HDMI/prj/MIPI_DDR3_HDMI/MIPI_DDR3_HDMI.srcs/utils_1/imports/synth_1/MIPI_DDR3_HDMI.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top MIPI_DDR3_HDMI_top -part xc7a75tfgg484-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MIPI_DDR3_HDMI_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file MIPI_DDR3_HDMI_top_utilization_synth.rpt -pb MIPI_DDR3_HDMI_top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
